export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
  TRANSACTIONS: "/transactions",
  PROPERTIES: "/properties",
  ALERTS: "/alerts",
  ALERT_NEW: "/alerts/new",
  BOOKMARKS: "/bookmarks",
  ADMIN: "/admin",
  PROPERTIES_NEW: "/properties/new",
  PROPERTY_DETAIL: (id: string) => `/properties/${id}`,
  TRANSACTIONS_NEW: "/transactions/new",
} as const;
