SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS alert_notifications;
DROP TABLE IF EXISTS price_alerts;
DROP TABLE IF EXISTS saved_properties;
DROP TABLE IF EXISTS resale_transactions;
DROP TABLE IF EXISTS gyms;
DROP TABLE IF EXISTS parks;
DROP TABLE IF EXISTS schools;
DROP TABLE IF EXISTS properties;
DROP TABLE IF EXISTS towns;
DROP TABLE IF EXISTS flat_models;
DROP TABLE IF EXISTS flat_types;
DROP TABLE IF EXISTS storeys;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;
